name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Se ejecuta cada 12 horas
  workflow_dispatch: # Permite ejecutarlo manualmente
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Generate Pac-Man
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate the pacman files
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman'

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
